version: '3.7'
services:
  java:
    container_name: java
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    environment:
      - CHOKIDAR_USEPOLLING=true